---
- name: Install Web Application
  hosts: target1
  become: yes
  tasks:
    - name: Install Python Dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip