---
- name: Install Web Application
  hosts: target1
  become: yes
  tasks:
    - name: Install Python Dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
    - name: Install Nginx
      yum:
        name: nginx
        state: installed
    - name: Start the service
      service:
        name: nginx
        state: started

    - name: Download sources for My-SQL Dependency
      get_url:
        url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
        dest: /opt/mysql

    - name: Install My-SQL Package
      yum:
        name: /opt/mysql/mysql-community-release-el7-5.noarch.rpm
        state: present
    - name: Install MYSQL
      yum:
        name: mysql-server
        state: present