---
- name: Install Web Application
  hosts: target1
  become: yes
  tasks:
    - name: Install Python Dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
    - name: Install Nginx
      yum:
        name: nginx
        state: installed
    - name: Start the service
      service:
        name: nginx
        state: started
    - name: Install My-SQL
      yum:
        name: mysql-server
        state: present